batch_size: 32
accum_grad: 2
max_epoch: 200
patience: none
# The initialization method for model parameters
init: xavier_uniform

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    #    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: dense_pretrain
decoder_conf:
    num_layers: 2
    hidden_size: 1024
    dropout: 0.0
    layer_norm_eps: 0.000000000001 

e2e_conf:
#    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0001
    #scheduler: warmuplr
    #scheduler_conf:
    #    warmup_steps: 20000
