# minibatch related
batch-size: 2
maxlen-in: 800
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: noam
epochs: 3
accum-grad: 1
patience: 2
transformer-lr: 5.0
transformer-warmup-steps: 10

# network architecture
## encoder related
etype: transformer
enc-block-arch:
        - type: transformer
          d_hidden: 32
          d_ff: 32
          heads: 2
enc-block-repeat: 2
## decoder related
dtype: transformer
dec-block-arch:
        - type: transformer
          d_hidden: 32
          d_ff: 30
          heads: 4
## joint network related
joint-dim: 30

# transducer related
## mtlalpha should be set to 1.0 (CTC) to use transducer
mtlalpha: 1.0
## switch to 'rnnt-att' to use transducer with attention
rnnt-mode: 'rnnt-att'
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
